elasticsearch:
  ca_cert_path: "/Users/leventesimon/dev/elastic/elasticsearch-8.9.0/config/certs/http_ca.crt"
http_server:
  http_address: ":8080"
vault:
  address: "http://localhost:8200"
  ca_cert_path: ""
  userpass_path: "userpass"
  kv_mount_path: "config/data"
  transit_path: "transit"
encrypt:
  - "outputs.*value$"